const PRICE_TIER_LABELS = {
  "0": "Sem desconto",
  "5": "5%",
  "10": "10%",
  "15": "15%",
  promo: "Promo especial",
};

const TOURS = [
  {
    id: "walking-tour",
    destination: "Santiago",
    name: "City Walking Tour",
    emoji: "🏙️🚶",
    highlights: ["Palácio de La Moneda", "Paseo Bandera", "Calle Nueva York", "Palácio de Justicia", "Plaza de Armas", "Catedral Metropolitana", "Cerro Santa Lucía", "Barrio Lastarria", "Parque Forestal"],
    departure: "a partir das 9h",
    duration: "a definir",
    included: ["guia bilíngue"],
    excluded: ["água", "transfer", "alimentação"],
    prices: { "0": 180, "5": 171, "10": 162, "15": 153, promo: 100 },
  },
  {
    id: "turistik-hop-on-hop-off",
    destination: "Santiago",
    name: "Turistik Hop On Hop Off",
    emoji: "🚌🏙️",
    highlights: ["Ônibus Hop On Hop Off por 1 dia", "Sky Costanera", "Cerro San Cristóbal", "Plaza de Armas", "Palácio de La Moneda", "Teleférico e funicular", "Áudio-guia em português"],
    departure: "a partir das 9h20",
    duration: "2 a 3h",
    included: ["ticket Hop On Hop Off ilimitado por 1 dia", "teleférico", "funicular", "áudio-guia", "mapa"],
    excluded: ["alimentação"],
    prices: { "0": 295, "5": 280, "10": 260, "15": 250 },
  },
  {
    id: "farellones",
    destination: "Santiago",
    name: "Ski Day Parque Farellones",
    emoji: "🏔️❄️",
    highlights: ["Parada no rental", "Lomas del Viento", "Parque Farellones", "Dia livre para aproveitar a neve e as atividades do parque"],
    departure: "entre 5h30 e 6h30",
    duration: "aproximadamente 9h",
    included: ["transfer ida e volta", "guia bilíngue"],
    excluded: ["roupas e acessórios de neve", "equipamentos", "ticket do parque", "alimentação"],
    prices: { "0": 295, "5": 280, "10": 260, "15": 250, promo: 199 },
  },
  {
    id: "valle-nevado",
    destination: "Santiago",
    name: "Ski Day Valle Nevado",
    emoji: "🏔️⛷️",
    highlights: ["Parada no rental", "Lomas del Viento", "Valle Nevado", "Centro de esqui a 3.000 metros de altitude"],
    departure: "entre 5h30 e 6h30",
    duration: "aproximadamente 9h",
    included: ["transfer ida e volta", "guia bilíngue"],
    excluded: ["roupas e acessórios de neve", "equipamentos", "ticket da estação", "alimentação"],
    prices: { "0": 295, "5": 280, "10": 260, "15": 250, promo: 199 },
  },
  {
    id: "el-colorado",
    destination: "Santiago",
    name: "Ski Day El Colorado",
    emoji: "🏔️🎿",
    highlights: ["Parada no rental", "Lomas del Viento", "Estação El Colorado", "Tempo para aproveitar a neve e as paisagens"],
    departure: "entre 5h30 e 6h30",
    duration: "aproximadamente 9h",
    included: ["transfer ida e volta", "guia bilíngue"],
    excluded: ["roupas e acessórios de neve", "equipamentos", "ticket da estação", "alimentação"],
    prices: { "0": 295, "5": 280, "10": 260, "15": 250, promo: 199 },
  },
  {
    id: "andes-panoramico",
    destination: "Santiago",
    name: "Andes Panorâmico",
    emoji: "🏔️📸",
    highlights: ["Parada no rental", "Lomas del Viento", "Farellones", "Valle Nevado", "Paradas panorâmicas para fotos e contato com a neve"],
    departure: "entre 5h30 e 6h30",
    duration: "aproximadamente 9h",
    included: ["transfer ida e volta", "guia bilíngue"],
    excluded: ["roupas e acessórios de neve", "equipamentos", "tickets", "alimentação"],
    prices: { "0": 295, "5": 280, "10": 260, "15": 250, promo: 199 },
  },
  {
    id: "portillo-laguna-del-inca",
    destination: "Santiago",
    name: "Portillo + Laguna del Inca",
    emoji: "🏔️💙",
    highlights: ["Parada para café da manhã", "Monumento Chacabuco", "Mirante Salto del Soldado", "Estrada Los Caracoles", "Laguna del Inca", "Hotel Portillo", "Picnic na Cordilheira"],
    departure: "entre 5h e 5h30",
    duration: "aproximadamente 9h",
    included: ["transfer ida e volta", "guia bilíngue", "picnic"],
    excluded: ["café da manhã"],
    prices: { "0": 325, "5": 308, "10": 292, "15": 276, promo: 237 },
  },
  {
    id: "vina-valparaiso",
    destination: "Santiago",
    name: "Viña del Mar + Valparaíso",
    emoji: "🌊🌸",
    highlights: ["Outlet de vinhos Río Tinto Casablanca", "Valparaíso e seus murais", "Cerro Alegre", "Plaza Sotomayor", "Viña del Mar", "Relógio de Flores", "Região costeira e praia", "Mirante dos leões-marinhos", "Museu Fonck e Moai em parada panorâmica"],
    departure: "entre 6h30 e 7h30",
    duration: "aproximadamente 9h",
    included: ["transfer ida e volta", "guia bilíngue", "degustação de vinho"],
    excluded: ["café da manhã", "almoço"],
    prices: { "0": 285, "5": 270, "10": 256, "15": 242, promo: 220 },
  },
  {
    id: "isla-negra-algarrobo-undurraga",
    destination: "Santiago",
    name: "Isla Negra + Algarrobo + Undurraga",
    emoji: "🌊🍷",
    highlights: ["Vinícola Undurraga", "Tour de aproximadamente 70 minutos", "Degustação de vinhos e taça de presente", "Algarrobo", "Vista para a piscina de San Alfonso del Mar", "Parada para almoço", "Isla Negra", "Região da Casa de Pablo Neruda", "Vista do Oceano Pacífico"],
    departure: "entre 7h30 e 8h30",
    duration: "aproximadamente 9h",
    included: ["transfer ida e volta", "guia bilíngue", "degustação de vinho"],
    excluded: ["café da manhã", "almoço", "ingresso do Museu Pablo Neruda"],
    prices: { "0": 469, "5": 445, "10": 421, "15": 398 },
  },
  {
    id: "undurraga",
    destination: "Santiago",
    name: "Vinícola Undurraga",
    emoji: "🍷🌿",
    highlights: ["Caminhada pelos vinhedos", "Bodegas subterrâneas", "Tour de aproximadamente 1h15", "Degustação de 3 vinhos", "Taça de presente"],
    departure: "opções pela manhã ou à tarde",
    duration: "aproximadamente 5h",
    included: ["transfer ida e volta", "guia bilíngue", "degustação de 3 vinhos", "taça de presente"],
    prices: { "0": 395, "5": 375, "10": 355, "15": 335 },
  },
  {
    id: "santa-rita",
    destination: "Santiago",
    name: "Vinícola Santa Rita",
    emoji: "🍷🏛️",
    highlights: ["Jardins e vinhedos históricos", "Antigas adegas", "Tour guiado de aproximadamente 1h30", "Degustação de 3 vinhos", "Taça de presente"],
    departure: "opções pela manhã ou à tarde",
    duration: "aproximadamente 5h",
    included: ["transfer ida e volta", "guia bilíngue", "degustação de 3 vinhos", "taça de presente"],
    prices: { "0": 435, "5": 413, "10": 391, "15": 369 },
  },
  {
    id: "concha-y-toro-premium",
    destination: "Santiago",
    name: "Concha y Toro - Experiência Premium",
    emoji: "🍷😈",
    highlights: ["Jardins históricos", "Vinhedos e variedades de uvas", "Adegas centenárias", "Experiência sensorial do Casillero del Diablo", "Degustação de 3 vinhos", "Taça oficial de presente"],
    departure: "opções pela manhã ou à tarde",
    duration: "aproximadamente 5h",
    included: ["transfer ida e volta", "visita guiada", "degustação de 3 vinhos", "taça oficial de presente"],
    prices: { "0": 435, "5": 413, "10": 391, "15": 369 },
  },
  {
    id: "concha-y-toro-marques",
    destination: "Santiago",
    name: "Concha y Toro - Tour do Marquês",
    emoji: "🍷👑",
    highlights: ["Experiência sensorial", "Adega Casillero del Diablo", "Adega de Guarda del Alto", "Mirante Concha y Toro", "Jardim de Variedades", "Degustação da linha Marques com queijos", "Experiência com enólogo"],
    departure: "opções pela manhã ou à tarde",
    duration: "aproximadamente 5h",
    included: ["transfer ida e volta", "guia bilíngue", "degustação de vinhos e queijos", "experiência com enólogo", "taça de presente"],
    prices: { "0": 680, "5": 646, "10": 612, "15": 578 },
  },
  {
    id: "concha-y-toro-centro-del-vino",
    destination: "Santiago",
    name: "Concha y Toro - Centro del Vino",
    emoji: "🍷🏰",
    highlights: ["Experiência sensorial", "Adega Casillero del Diablo", "Adega de Guarda del Alto", "Mirante Concha y Toro", "Jardim de Variedades", "Visita pelos arredores do parque"],
    departure: "opções pela manhã ou à tarde",
    duration: "aproximadamente 5h",
    included: ["transfer ida e volta", "guia bilíngue", "degustação de 4 vinhos", "taça de presente"],
    prices: { "0": 530, "5": 504, "10": 477, "15": 451 },
  },
  {
    id: "concha-y-toro-noturno",
    destination: "Santiago",
    name: "Concha y Toro - Tour Noturno",
    emoji: "🌙🍷",
    highlights: ["Vinícola iluminada à noite", "Lenda do Casillero del Diablo", "Vinhedos e adegas centenárias", "Degustação de 4 vinhos", "Jantar com menu de 3 tempos"],
    departure: "no período da noite",
    duration: "aproximadamente 5h",
    included: ["transfer ida e volta", "guia bilíngue", "taça de espumante", "degustação de 4 vinhos", "jantar de 3 tempos", "taça de presente"],
    prices: { "0": 905, "5": 860, "10": 815, "15": 769 },
  },
  {
    id: "alyan-sunset",
    destination: "Santiago",
    name: "Vinícola Alyan Sunset",
    emoji: "🌅🍷",
    highlights: ["Alyan Family Wines", "Paisagens do Vale do Maipo", "Degustação com enólogo", "Queijos e vinhos", "Jantar", "Pôr do sol entre vinhedos e Cordilheira"],
    departure: "entre 14h30 e 15h",
    duration: "até depois do pôr do sol",
    included: ["transfer ida e volta", "guia bilíngue", "degustação de queijos e vinhos", "enólogo", "taça de presente", "jantar"],
    note: "Experiência exclusiva para maiores de 18 anos.",
    prices: { "0": 670, "5": 637, "10": 603, "15": 570 },
  },
  {
    id: "monteluz-sunset",
    destination: "Santiago",
    name: "Monteluz Sunset",
    emoji: "🌅🎧",
    highlights: ["Tour pela casona histórica", "Degustação de vinhos selecionados", "Tábuas e petiscos gourmet", "Pôr do sol em varanda panorâmica", "Festa com DJ e celebração noturna"],
    departure: "entre 14h45 e 15h20",
    duration: "até depois do pôr do sol",
    included: ["transfer ida e volta", "guia bilíngue", "ticket da vinícola", "degustação de vinhos", "petiscos gourmet", "festa com DJ"],
    prices: { "0": 580, "5": 551, "10": 522, "15": 493 },
  },
  {
    id: "parque-safari",
    destination: "Santiago",
    name: "Parque Safari",
    emoji: "🦁🦒",
    highlights: ["Safari em contato com a natureza", "Observação de leões e tigres", "Fauna chilena", "Ticket geral", "Ticket de felinos", "Ticket de herbívoros"],
    departure: "pela manhã",
    duration: "aproximadamente 5h",
    included: ["transfer ida e volta", "guia bilíngue", "ticket geral", "ticket de felinos", "ticket de herbívoros"],
    excluded: ["alimentação"],
    prices: { "0": 480, "5": 456, "10": 432, "15": 408, promo: 375 },
  },
  {
    id: "zerando-sunset",
    destination: "Santiago",
    name: "Zerando Sunset na Cordilheira",
    emoji: "🏔️🎶",
    highlights: ["Parada no rental", "Estação El Colorado", "Casa Zerando e mirante para fotos", "Evento sunset no Taringuita", "Música eletrônica e vista para o Vale de Farellones"],
    departure: "entre 10h e 11h",
    duration: "até depois do pôr do sol",
    included: ["transfer ida e volta"],
    excluded: ["alimentação", "bebidas no Taringuita"],
    prices: { "0": 1000 },
  },
  {
    id: "infinitum-3k",
    destination: "Santiago",
    name: "Experiência Infinitum 3K",
    emoji: "🏔️🎧",
    highlights: ["Parada em loja de aluguel", "Farellones", "La Parva", "Valle Nevado", "Evento sunset no El Montañés", "DJ e música ao vivo a mais de 3.000 metros"],
    departure: "entre 9h e 10h",
    duration: "até depois do pôr do sol",
    included: ["transfer ida e volta", "entrada para o evento", "DJ e música ao vivo"],
    excluded: ["roupas de neve", "alimentação"],
    note: "Experiência exclusiva para maiores de 18 anos.",
    prices: { "0": 690, "5": 656, "10": 621, "15": 587 },
  },
  {
    id: "moto-de-neve",
    destination: "Santiago",
    name: "Aventura de Moto de Neve",
    emoji: "🏔️🏍️",
    highlights: ["Rental de roupas de neve", "Cajón del Maipo", "Instruções de segurança", "Passeio de moto de neve por aproximadamente 2h", "Refúgio Alemán", "Casa de Chocolate"],
    departure: "às 6h",
    duration: "aproximadamente 8h",
    included: ["transfer ida e volta", "passeio de moto de neve"],
    excluded: ["alimentação", "aluguel de roupas"],
    note: "Passeio em dupla. CNH categoria B obrigatória para pilotar. Idade mínima de 12 anos.",
    prices: { "0": 1800, "5": 1710, "10": 1620, "15": 1530 },
  },
  {
    id: "tour-astronomico",
    destination: "Atacama",
    name: "Tour Astronômico",
    emoji: "🔭✨",
    highlights: ["Observação de estrelas e planetas", "Constelações do céu do Atacama", "Observação com telescópios", "Explicação com guia especializado", "Astrofotografia"],
    departure: "às 19h45 ou 20h45",
    duration: "aproximadamente 3h",
    included: ["transfer ida e volta", "guia especializado", "telescópios", "snack", "astrofotografia"],
    excluded: ["fotos adicionais"],
    note: "Atividade sujeita às condições climáticas e à fase da lua.",
    prices: { "0": 290, "5": 276, "10": 261, "15": 247, promo: 199 },
  },
  {
    id: "valle-de-la-luna",
    destination: "Atacama",
    name: "Valle de la Luna",
    emoji: "🌙🏜️",
    highlights: ["Formações rochosas", "Dunas e paisagens lunares", "Caminhada pelo deserto", "Pôr do sol no Atacama"],
    departure: "entre 15h30 e 16h30",
    duration: "aproximadamente 4h",
    included: ["transfer ida e volta", "guia bilíngue", "snack", "ticket"],
    prices: { "0": 375, "5": 356, "10": 337, "15": 318 },
  },
  {
    id: "geyser-del-tatio",
    destination: "Atacama",
    name: "Geyser del Tatio",
    emoji: "🌋🌅",
    highlights: ["Campo geotérmico a mais de 4.000 metros", "Nascer do sol entre gêiseres", "Vapores e paisagens altiplânicas", "Café da manhã no deserto"],
    departure: "entre 4h30 e 5h10",
    duration: "aproximadamente 7h",
    included: ["transfer ida e volta", "guia bilíngue", "café da manhã", "ticket"],
    note: "O passeio supera 4.000 metros de altitude e pode registrar temperaturas abaixo de 0 °C.",
    prices: { "0": 495, "5": 470, "10": 445, "15": 420 },
  },
  {
    id: "piedras-rojas",
    destination: "Atacama",
    name: "Lagunas Altiplânicas + Piedras Rojas + Laguna Chaxa",
    emoji: "🦩🏔️",
    highlights: ["Piedras Rojas", "Lagunas Miscanti e Miñiques", "Laguna Chaxa", "Flamingos", "Vulcões e salares do Altiplano"],
    departure: "entre 7h e 7h40",
    duration: "aproximadamente 11h",
    included: ["transfer ida e volta", "guia bilíngue", "café da manhã", "almoço", "tickets"],
    prices: { "0": 755, "5": 715, "10": 679, "15": 640 },
  },
  {
    id: "valle-del-arcoiris",
    destination: "Atacama",
    name: "Valle del Arcoíris + Yerbas Buenas",
    emoji: "🌈",
    highlights: ["Montanhas coloridas", "Valle del Arcoíris", "Petróglifos de Yerbas Buenas", "Cultura e história ancestral"],
    departure: "entre 7h e 7h40",
    duration: "aproximadamente 6h",
    included: ["transfer ida e volta", "guia bilíngue", "café da manhã", "ticket"],
    prices: { "0": 279, "5": 266, "10": 252, "15": 238 },
  },
  {
    id: "baltinache",
    destination: "Atacama",
    name: "Lagunas Escondidas de Baltinache",
    emoji: "💧🧂",
    highlights: ["Lagoas azul-turquesa", "Paisagens de sal", "Flutuação natural", "Experiência de banho no deserto"],
    departure: "7h/7h40 ou 14h/14h40",
    duration: "aproximadamente 4 a 5h",
    included: ["transfer ida e volta", "guia bilíngue", "café da manhã ou snack", "ticket"],
    prices: { "0": 430, "5": 408, "10": 387, "15": 365 },
  },
  {
    id: "vallecito-magic-bus",
    destination: "Atacama",
    name: "Vallecito Magic Bus",
    emoji: "🚌🏜️",
    highlights: ["Magic Bus", "Cordilheira de Sal", "Llano de la Paciencia", "Pôr do sol no deserto"],
    departure: "entre 15h30 e 16h10",
    duration: "aproximadamente 4h",
    included: ["transfer ida e volta", "guia bilíngue", "snack"],
    prices: { "0": 279, "5": 265, "10": 251, "15": 237, promo: 210 },
  },
  {
    id: "laguna-cejar",
    destination: "Atacama",
    name: "Laguna Cejar + Tebinquinche + Ojos del Salar",
    emoji: "💦🌅",
    highlights: ["Laguna Piedra", "Flutuação em águas salgadas", "Laguna Cejar", "Ojos del Salar", "Entardecer na Laguna Tebinquinche"],
    departure: "entre 14h e 14h40",
    duration: "aproximadamente 4h",
    included: ["transfer ida e volta", "guia", "snack", "entrada na Laguna Cejar"],
    prices: { "0": 435, "5": 413, "10": 390, "15": 369 },
  },
  {
    id: "ruta-de-los-salares",
    destination: "Atacama",
    name: "Ruta de los Salares",
    emoji: "🏔️🧂",
    highlights: ["Vulcão Licancabur", "Monjes de la Pacana", "Salar de Quisquiro", "Águas Calientes", "Salar de Pujsa", "Paisagens acima de 4.000 metros"],
    departure: "entre 7h e 7h40",
    duration: "aproximadamente 7h",
    included: ["transfer ida e volta", "guia bilíngue", "café da manhã", "almoço"],
    prices: { "0": 429, "5": 407, "10": 386, "15": 364 },
  },
  {
    id: "termas-puritama",
    destination: "Atacama",
    name: "Termas de Puritama",
    emoji: "♨️🏜️",
    highlights: ["Águas termais entre 28 °C e 31 °C", "Cânion no Deserto do Atacama", "Tempo para banho e relaxamento"],
    departure: "8h/8h40 ou 13h/13h40",
    duration: "aproximadamente 5h",
    included: ["transfer ida e volta", "ticket"],
    excluded: ["alimentação"],
    prices: { "0": 499, "5": 475, "10": 450, "15": 425 },
  },
  {
    id: "termas-purilibre",
    destination: "Atacama",
    name: "Termas Purilibre",
    emoji: "🥾♨️",
    highlights: ["Caminhada de aproximadamente 40 minutos", "Cânion cercado pela natureza", "Piscinas termais naturais", "Experiência de trekking e relaxamento"],
    departure: "8h/8h40 ou 13h/13h40",
    duration: "aproximadamente 5h",
    included: ["transfer ida e volta", "ticket"],
    note: "Não há local para trocar de roupa; recomenda-se sair de San Pedro com roupa de banho.",
    prices: { "0": 285, "5": 267, "10": 253, "15": 239, promo: 200 },
  },
  {
    id: "volcan-lascar",
    destination: "Atacama",
    name: "Vulcão Láscar",
    emoji: "🌋🥾",
    highlights: ["Expedição ao Vulcão Láscar", "Caminhada de 2 a 3 horas até o cume", "Vista para a cratera", "Paisagens vulcânicas do Atacama"],
    departure: "entre 5h e 5h40",
    duration: "aproximadamente 11h",
    included: ["transfer ida e volta", "guia bilíngue", "café da manhã", "ração de marcha", "bastão para trekking", "ticket"],
    prices: { "0": 1125, "5": 1068, "10": 1012, "15": 956 },
  },
];

window.TOURS = TOURS;
